date.timezone=Europe/Moscow
default_charset=UTF-8

expose_php=0
display_errors=0
log_errors=1
error_reporting=E_ALL

upload_max_filesize=256M
post_max_size=256M
max_execution_time=600
max_input_time=600

realpath_cache_size=4096K
realpath_cache_ttl=600
